repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true
        require_serial: false
      - id: typecheck
        name: Typecheck
        entry: uv run ty check
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true